// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Title         string
	Author        string
	Notes         string
	Image         string
	UserID        uuid.UUID
}

type UserFollow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	BookID    uuid.UUID
}

type Post struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description sql.NullString
	PublishedAt time.Time
	Url         string
	BookID      uuid.UUID
}

type User struct {
	ID        uuid.UUID 
	CreatedAt time.Time 
	UpdatedAt time.Time 
	Name      string    
	Email     string    
	Password  string   
	Image     string   
	ApiKey    string   
}

